
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04]
        cpp_compiler: [g++-12, g++-14, clang++-16, clang++-18]
        build_type: [Release, Debug]

        include:
          - cpp_compiler: g++-12
            c_compiler: gcc-12
          - cpp_compiler: g++-14
            c_compiler: gcc-14
          - cpp_compiler: clang++-16
            c_compiler: clang-16
          - cpp_compiler: clang++-18
            c_compiler: clang-18

    steps:
    - uses: actions/checkout@v4
    - name: install compilers
      run: sudo apt install -y gcc-12 gcc-14 clang-16 clang-18
    - name: install dependencies
      run: sudo apt install -y cmake libhdf5-dev

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Run Unittests
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./scribe_tests
    
  build_macos:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest]
        cpp_compiler: [clang++]
        build_type: [Release, Debug]

        include:
          - cpp_compiler: clang++
            c_compiler: clang

    steps:
    - uses: actions/checkout@v4
    #- name: install compilers
    #  run: sudo apt install -y gcc-12 gcc-14 clang-16 clang-18
    - name: install dependencies
      run: brew install cmake hdf5

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Run Unittests
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./scribe_tests
